datasets:
  dataset_1:
    name: "8 Donor PBMC AH"
    geo_accession: "GSM4904942"
    hto_file: "data/dataset_1/hto/GSM4904942_8donor_PBMC_AH_MULTI_matrix.csv"
    rna_dir: "data/dataset_1/rna/"
    n_donors: 8
    hto_columns:
      - Bar9
      - Bar10
      - Bar11
      - Bar12
      - Bar13
      - Bar14
      - Bar15
      - Bar16
    numi_columns_to_drop:
      - nUMI
      - nUMI_Total
    demultiplex:
        n_rounds: 3
        rescue_threshold: 10
    notes: >
      - deMULTIplex2 internally filters cells before classification - missing cells
      are reassigned as negative in output to maintain consistent total of 5159
      across all methods

  dataset_2:
    name: 
    geo_accession: "GSM4904930"
    hto_file: "data/dataset_2/hto/GSM490493...csv"
    rna_dir: 
    n_donors: 8
    hto_columns:
      - Bar1
      - Bar2
      - Bar3
      - Bar4
      - Bar5
      - Bar6
      - Bar7
      - Bar8
    demultiplex:
        n_rounds: 4
        rescue_threshold: 20
    numi_columns_to_drop:
      - nUMI
      - nUMI_Total